# Generated by Django 5.1.7 on 2025-04-02 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datinguser",
            name="candidate",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dating_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
