# Generated by Django 5.1.7 on 2025-04-02 10:41

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referrer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="candidateinquiry",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="candidateinquiry",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="candidateinquiry",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="candidateinquiry",
            name="mother_tongue",
        ),
        migrations.RemoveField(
            model_name="candidateinquiry",
            name="preferences",
        ),
        migrations.RemoveField(
            model_name="consultant",
            name="active",
        ),
        migrations.RemoveField(
            model_name="consultant",
            name="user",
        ),
        migrations.RemoveField(
            model_name="datinguser",
            name="referral_code",
        ),
        migrations.RemoveField(
            model_name="datinguser",
            name="user",
        ),
        migrations.RemoveField(
            model_name="referrercode",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="referrercode",
            name="referral_code",
        ),
        migrations.AddField(
            model_name="candidateinquiry",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="candidateinquiry",
            name="referral_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.referrercode",
            ),
        ),
        migrations.AddField(
            model_name="consultant",
            name="email",
            field=models.EmailField(default=123456, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultant",
            name="name",
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datinguser",
            name="candidate",
            field=models.OneToOneField(
                default=123455,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.candidateinquiry",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datinguser",
            name="gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="datinguser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
        migrations.AddField(
            model_name="referrercode",
            name="code",
            field=models.CharField(
                default=core.models.generate_unique_code, max_length=10, unique=True
            ),
        ),
        migrations.AddField(
            model_name="referrercode",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="referrercode",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
        migrations.AlterField(
            model_name="candidateinquiry",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="candidateinquiry",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="datinguser",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="candidateinquiry",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.referrer",
            ),
        ),
        migrations.AlterField(
            model_name="referrercode",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codes",
                to="core.referrer",
            ),
        ),
    ]
