# Generated by Django 5.1.7 on 2025-04-03 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_candidateinquiry_referral_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datinguser",
            name="referrer_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.referrercode",
            ),
        ),
    ]
