# Generated by Django 5.1.7 on 2025-04-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_datinguser_referrer_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consultant",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="referrer",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="consultant",
            name="last_name",
            field=models.CharField(default="unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datinguser",
            name="first_name",
            field=models.CharField(default="unknwon", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datinguser",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="datinguser",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referrer",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
    ]
